### ISSUE TITLE
Make the buttons change color after "bet placed"

### ISSUE THREAD

**Issue by skeddles** [diceroll123/neofoodclub#324]
If they changed color it would make it a lot easy to see which button you have to click next at a glance. 

Perhaps they could be red by default and change to their current gray color after the bets placed.

**Comment by diceroll123** [comment]
Thanks for the suggestion!

I've added this, but I went with green -- since red is more of a "danger" color. We'll see what the community thinks though! 😄

**Comment by skeddles** [comment]
Looks great to me, thanks for making the change! 
You are probably right to go with green.
